python train_transformer.py --data_path data_imu/activity_20/dataset_user_1.csv --batch_size 128 --num_epochs 200 --modalities acc_gyr_mag --experiment_name activity_20/cross_user/cnn_transformer/acc_gyr_mag/bsz128_resample_all;\
python train_transformer.py --data_path data_imu/activity_20/dataset_user_2.csv --batch_size 128 --num_epochs 200 --modalities acc_gyr_mag --experiment_name activity_20/cross_user/cnn_transformer/acc_gyr_mag/bsz128_resample_all;\
python train_transformer.py --data_path data_imu/activity_20/dataset_user_3.csv --batch_size 128 --num_epochs 200 --modalities acc_gyr_mag --experiment_name activity_20/cross_user/cnn_transformer/acc_gyr_mag/bsz128_resample_all;\
python train_transformer.py --data_path data_imu/activity_20/dataset_user_4.csv --batch_size 128 --num_epochs 200 --modalities acc_gyr_mag --experiment_name activity_20/cross_user/cnn_transformer/acc_gyr_mag/bsz128_resample_all;\
python train_transformer.py --data_path data_imu/activity_20/dataset_user_5.csv --batch_size 128 --num_epochs 200 --modalities acc_gyr_mag --experiment_name activity_20/cross_user/cnn_transformer/acc_gyr_mag/bsz128_resample_all;\
python train_transformer.py --data_path data_imu/activity_20/dataset_user_6.csv --batch_size 128 --num_epochs 200 --modalities acc_gyr_mag --experiment_name activity_20/cross_user/cnn_transformer/acc_gyr_mag/bsz128_resample_all;\
python train_transformer.py --data_path data_imu/activity_20/dataset_user_7.csv --batch_size 128 --num_epochs 200 --modalities acc_gyr_mag --experiment_name activity_20/cross_user/cnn_transformer/acc_gyr_mag/bsz128_resample_all;\
python train_transformer.py --data_path data_imu/activity_20/dataset_user_8.csv --batch_size 128 --num_epochs 200 --modalities acc_gyr_mag --experiment_name activity_20/cross_user/cnn_transformer/acc_gyr_mag/bsz128_resample_all;\
python train_transformer.py --data_path data_imu/activity_20/dataset_user_9.csv --batch_size 128 --num_epochs 200 --modalities acc_gyr_mag --experiment_name activity_20/cross_user/cnn_transformer/acc_gyr_mag/bsz128_resample_all;\
python train_transformer.py --data_path data_imu/activity_20/dataset_user_10.csv --batch_size 128 --num_epochs 200 --modalities acc_gyr_mag --experiment_name activity_20/cross_user/cnn_transformer/acc_gyr_mag/bsz128_resample_all;\
python train_transformer.py --data_path data_imu/activity_20/dataset_user_11.csv --batch_size 128 --num_epochs 200 --modalities acc_gyr_mag --experiment_name activity_20/cross_user/cnn_transformer/acc_gyr_mag/bsz128_resample_all;\
python train_transformer.py --data_path data_imu/activity_20/dataset_user_12.csv --batch_size 128 --num_epochs 200 --modalities acc_gyr_mag --experiment_name activity_20/cross_user/cnn_transformer/acc_gyr_mag/bsz128_resample_all;\
python train_transformer.py --data_path data_imu/activity_20/dataset_user_13.csv --batch_size 128 --num_epochs 200 --modalities acc_gyr_mag --experiment_name activity_20/cross_user/cnn_transformer/acc_gyr_mag/bsz128_resample_all;\
python train_transformer.py --data_path data_imu/activity_20/dataset_user_14.csv --batch_size 128 --num_epochs 200 --modalities acc_gyr_mag --experiment_name activity_20/cross_user/cnn_transformer/acc_gyr_mag/bsz128_resample_all;\
python train_transformer.py --data_path data_imu/activity_20/dataset_user_15.csv --batch_size 128 --num_epochs 200 --modalities acc_gyr_mag --experiment_name activity_20/cross_user/cnn_transformer/acc_gyr_mag/bsz128_resample_all;\
python train_transformer.py --data_path data_imu/activity_20/dataset_user_16.csv --batch_size 128 --num_epochs 200 --modalities acc_gyr_mag --experiment_name activity_20/cross_user/cnn_transformer/acc_gyr_mag/bsz128_resample_all;\
python train_transformer.py --data_path data_imu/activity_20/dataset_user_17.csv --batch_size 128 --num_epochs 200 --modalities acc_gyr_mag --experiment_name activity_20/cross_user/cnn_transformer/acc_gyr_mag/bsz128_resample_all;\
python train_transformer.py --data_path data_imu/activity_20/dataset_user_18.csv --batch_size 128 --num_epochs 200 --modalities acc_gyr_mag --experiment_name activity_20/cross_user/cnn_transformer/acc_gyr_mag/bsz128_resample_all;\
python train_transformer.py --data_path data_imu/activity_20/dataset_user_19.csv --batch_size 128 --num_epochs 200 --modalities acc_gyr_mag --experiment_name activity_20/cross_user/cnn_transformer/acc_gyr_mag/bsz128_resample_all;\
python train_transformer.py --data_path data_imu/activity_20/dataset_user_20.csv --batch_size 128 --num_epochs 200 --modalities acc_gyr_mag --experiment_name activity_20/cross_user/cnn_transformer/acc_gyr_mag/bsz128_resample_all;\
# python train_transformer.py --data_path data_imu/activity_20/dataset_user_21.csv --batch_size 128 --num_epochs 200 --modalities acc_gyr_mag --experiment_name activity_20/cross_user/cnn_transformer/acc_gyr_mag/bsz128_resample_all;\
# python train_transformer.py --data_path data_imu/activity_20/dataset_user_22.csv --batch_size 128 --num_epochs 200 --modalities acc_gyr_mag --experiment_name activity_20/cross_user/cnn_transformer/acc_gyr_mag/bsz128_resample_all;\
# python train_transformer.py --data_path data_imu/activity_20/dataset_user_23.csv --batch_size 128 --num_epochs 200 --modalities acc_gyr_mag --experiment_name activity_20/cross_user/cnn_transformer/acc_gyr_mag/bsz128_resample_all;\
# python train_transformer.py --data_path data_imu/activity_20/dataset_user_24.csv --batch_size 128 --num_epochs 200 --modalities acc_gyr_mag --experiment_name activity_20/cross_user/cnn_transformer/acc_gyr_mag/bsz128_resample_all;\
# python train_transformer.py --data_path data_imu/activity_20/dataset_user_25.csv --batch_size 128 --num_epochs 200 --modalities acc_gyr_mag --experiment_name activity_20/cross_user/cnn_transformer/acc_gyr_mag/bsz128_resample_all;\
# python train_transformer.py --data_path data_imu/activity_20/dataset_user_26.csv --batch_size 128 --num_epochs 200 --modalities acc_gyr_mag --experiment_name activity_20/cross_user/cnn_transformer/acc_gyr_mag/bsz128_resample_all;\
# python train_transformer.py --data_path data_imu/activity_20/dataset_user_27.csv --batch_size 128 --num_epochs 200 --modalities acc_gyr_mag --experiment_name activity_20/cross_user/cnn_transformer/acc_gyr_mag/bsz128_resample_all;\
# python train_transformer.py --data_path data_imu/activity_20/dataset_user_28.csv --batch_size 128 --num_epochs 200 --modalities acc_gyr_mag --experiment_name activity_20/cross_user/cnn_transformer/acc_gyr_mag/bsz128_resample_all;\
# python train_transformer.py --data_path data_imu/activity_20/dataset_user_29.csv --batch_size 128 --num_epochs 200 --modalities acc_gyr_mag --experiment_name activity_20/cross_user/cnn_transformer/acc_gyr_mag/bsz128_resample_all;\
# python train_transformer.py --data_path data_imu/activity_20/dataset_user_30.csv --batch_size 128 --num_epochs 200 --modalities acc_gyr_mag --experiment_name activity_20/cross_user/cnn_transformer/acc_gyr_mag/bsz128_resample_all;\